---
network_devices:
  - name: "Demo_Switch_1"
    description: "Access Switch 1 - managed by Ansible"
    ip_address: "10.1.254.102"
    mask: 32
    shared_secret: "ISEisC00L"
    location: "Minnesota"
    device_type: "Switches"
    state: "present"

  - name: "Demo_Switch_2"
    description: "Access Switch 2 - managed by Ansible"
    ip_address: "10.1.254.103"
    mask: 32
    shared_secret: "ISEisC00L"
    location: "Minnesota"
    device_type: "Switches"
    state: "present"

  - name: "Demo_Switch_3"
    description: "Access Switch 3 - managed by Ansible"
    ip_address: "10.1.254.104"
    mask: 32
    shared_secret: "ISEisC00L"
    location: "Minnesota"
    device_type: "Switches"
    state: "present"

  - name: "Demo_Switch_4"
    description: "Access Switch 4 - managed by Ansible"
    ip_address: "10.1.254.105"
    mask: 32
    shared_secret: "ISEisC00L"
    location: "Iowa"
    device_type: "Switches"
    state: "present"
